### ISSUE TITLE
langchain-visualizer on clean env got the error

### ISSUE THREAD

**Issue by mkamalov** [amosjyng/langchain-visualizer#76]
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.

```
from langchain_visualizer import visualize_embeddings

if "__main__" == __name__:
    visualize_embeddings()
```

**Comment by amosjyng** [comment]
Sorry, I can't reproduce this... This project doesn't use pydantic anywhere. Can you try again on v0.0.30 and see if the problem still persists?

**Comment by denysthegitmenace** [comment]
Same on my end. 
<img width="904" alt="Screenshot 2023-09-17 at 12 32 45" src="https://github.com/amosjyng/langchain-visualizer/assets/10329935/d5b4c5aa-801d-45fc-bd7e-faa95bc8c063">

**Comment by amosjyng** [comment]
Ah thanks for providing the stack trace! It turns out this is caused by https://github.com/oughtinc/ice/issues/319

I've set this to explicitly depend on pydantic v1 instead while the above issue is still open. Please try seeing if v0.0.31 of langchain-visualizer works for you. Feel free to reopen this if it's still failing :)
